#!/bin/bash
trap ctrl_c INT

function ctrl_c() {
        echo "Get Ctrl-c exit."
        exit 1
}

function contains() {
    if [[ $1 =~ (^|[[:space:]])$2($|[[:space:]]) ]];
    then
        return 0
    else
        return 1 
    fi
}

ALL_SERVICES="nova glance neutron keystone cinder heat designate octavia quotas"
TIMESTAMP=$(date +%F-%H-%M-%S)
ECHO_STRING=

if [ "$#" -eq 0 ];
then 
    echo "Select service form $ALL_SERVICES"
    echo "or all"
    exit 0

else
    services="$@"
fi 

mkdir -p /root/output/$TIMESTAMP

if [ "$1" == "all" ];
then
    rally task start --task /root/openstack/task.yaml --task-args-file /root/openstack/task_arguments.yaml --tag "all-$TIMESTAMP"
    rally task report --html-static --uuid $(rally task list --uuids-only --tag "all-$TIMESTAMP") --out /root/output/$TIMESTAMP/all.html
    exit 0
fi


for s in $services
do  
    contains "$ALL_SERVICES" $s 
    if [ $? -gt 0 ];
    then 
        echo "$s not in $ALL_SERVICES"
        exit 1
    fi
    JSON_STRING=$( jq -n \
                      --arg service "$s" \
                      '{service_list: [ $service ]}' )
    rally task start --task /root/openstack/task.yaml --task-args-file /root/openstack/task_arguments.yaml --task-args "$JSON_STRING" --tag "$s-$TIMESTAMP"
    
    rally task report --html-static --uuid $(rally task list --uuids-only --tag "$s-$TIMESTAMP") --out /root/output/$TIMESTAMP/$s.html
    ECHO_STRING="$ECHO_STRING \n$s report path: /root/output/$TIMESTAMP/$s.html"
done

echo
echo -e "$ECHO_STRING"
