#!/bin/bash
trap ctrl_c INT

function ctrl_c() {
        echo "Get Ctrl-c exit."
        exit 1
}

if [ "x$@" == "x" ];
then 
    echo "Select a service form nova,glance,neutron,keystone,cinder,heat,designate,octavia."
    echo "or all"
    exit 0

else
    services="$@"
fi 

if [ "$@" == "all" ];
then
    services="nova neutron keystone cinder glance heat designate octavia"
fi
TIMESTAMP=$(date +_%F-%H-%M-%S)
mkdir -p output/$TIMESTAMP
for s in $services
do
    JSON_STRING=$( jq -n \
                      --arg service "$s" \
                      '{service_list: [ $service ]}' )
    rally task start --task /root/openstack/task.yaml --task-args-file /root/openstack/task_arguments.yaml --task-args "$JSON_STRING" --tag "$s$TIMESTAMP"
    
    rally task report --html-static --uuid $(rally task list --uuids-only --tag "$s$TIMESTAMP") --out output/$TIMESTAMP/$s$TIMESTAMP.html
done
