#!/bin/bash
trap ctrl_c INT

function ctrl_c() {
        echo "Get Ctrl-c exit."
        exit 1
}

function contains() {
    [[ $1 =~ (^|[[:space:]])$2($|[[:space:]]) ]] && exit(0) || exit(1)
}

ALL_SERVICES="nova glance neutron keystone cinder heat designate octavia quotas"
TIMESTAMP=$(date +%F-%H-%M-%S)
ECHO_STRING=

if [ "$#" -eq 0 ];
then 
    echo "Select service form $ALL_SERVICES"
    echo "or all"
    exit 0

else
    services="$@"
fi 

if [ "$1" == "all" ];
then
    services=$ALL_SERVICES
fi

mkdir -p output/$TIMESTAMP
for s in $services
do  
    contains $ALL_SERVICES $s 
    if [ $? -gt 0 ];
    then 
        echo "$s not in $ALL_SERVICES"
        exit 1
    fi
    JSON_STRING=$( jq -n \
                      --arg service "$s" \
                      '{service_list: [ $service ]}' )
    rally task start --task /root/openstack/task.yaml --task-args-file /root/openstack/task_arguments.yaml --task-args "$JSON_STRING" --tag "$s-$TIMESTAMP"
    
    rally task report --html-static --uuid $(rally task list --uuids-only --tag "$s-$TIMESTAMP") --out output/$TIMESTAMP/$s.html
    ECHO_STRING="$ECHO_STRING \n$s report path: output/$TIMESTAMP/$s.html"
done

echo
echo -e "$ECHO_STRING"
